### ISSUE TITLE
Known issue - JavaScript Error Under QQ Scenes

### ISSUE THREAD

**Issue by hifocus** [hifocus/merger#1]
Please be aware that `merger` should not be used as production at this time.

![image](https://user-images.githubusercontent.com/30528433/50368402-453e8e80-05c3-11e9-865c-d41d4bcb82ae.png)

We are trying out best to make changes.

**Comment by LF112** [comment]
I think it belongs to the browser plug-in to report an error

**Comment by hifocus** [comment]
![image](https://user-images.githubusercontent.com/30528433/50372580-f49f5380-060b-11e9-90c0-3f7aba2cccb4.png)

Issue detected with the Zhihu API. Attempting to resolve the problem without replacing the API.

**Comment by hifocus** [comment]
URL should be Unicode encoded. Compare between:

`https://i.qianbao.qq.com/wallet/sqrcode.htm?m=tenpay&f=wallet&a=1&ac=26E3D12F23952F04A9553D36B31F18BC3AEA141B073F9DD9BC3747C823819645&u=1031092401&n=惶心`

Which is:
 ![](https://www.zhihu.com/qrcode?url=https://i.qianbao.qq.com/wallet/sqrcode.htm?m=tenpay&f=wallet&a=1&ac=26E3D12F23952F04A9553D36B31F18BC3AEA141B073F9DD9BC3747C823819645&u=1031092401&n=%E6%83%B6%E5%BF%83)

And

`https://www.zhihu.com/qrcode?url=https%3a%2f%2fi.qianbao.qq.com%2fwallet%2fsqrcode.htm%3fm%3dtenpay%26f%3dwallet%26a%3d1%26ac%3d26E3D12F23952F04A9553D36B31F18BC3AEA141B073F9DD9BC3747C823819645%26u%3d1031092401%26n%3d%E6%83%B6%E5%BF%83`

Which is:
![](https://www.zhihu.com/qrcode?url=https%3a%2f%2fi.qianbao.qq.com%2fwallet%2fsqrcode.htm%3fm%3dtenpay%26f%3dwallet%26a%3d1%26ac%3d26E3D12F23952F04A9553D36B31F18BC3AEA141B073F9DD9BC3747C823819645%26u%3d1031092401%26n%3d%e6%83%b6%e5%bf%83)

**Comment by hifocus** [comment]
Fixed.
