### ISSUE TITLE
微信需要二次扫描才能识别

### ISSUE THREAD

**Issue by GenesisAN** [hifocus/merger#10]
我不确定这是否是一个不可解决的技术问题，在使用微信扫描合并后的二维码时，网页会弹出微信的二维码，此时你对着二维码长按再选择扫描二维码才能出来付款页面，而支付宝则没有这个问题，一扫描就可以支付。

**Comment by hifocus** [comment]
微信对外部调用比较严格，所以必须二次扫码。QQ 同理。

支付宝则宽松得多，甚至在后续版本还会添加更好的支持。
