### ISSUE TITLE
似乎没法获取gravatar的头像？

### ISSUE THREAD

**Issue by JohnsonRan** [hifocus/merger#13]
我在github pages整了一个，
profile那里输入gravatar的用户名后没法获取头像
图床的也一样嗷

**Comment by hifocus** [comment]
确实是一个 Bug，非常抱歉，尽快排查解决。

**Comment by hifocus** [comment]
> 我在github pages整了一个，
> profile那里输入gravatar的用户名后没法获取头像
> 图床的也一样嗷

问题已被修复，更新新版本即可；gravatar 应该是工作的，如果不行请提供你的配置。
