### ISSUE TITLE
增加捐赠列表？

### ISSUE THREAD

**Issue by Littlegolden** [hifocus/merger#14]
有没有可能在网页里加入一个捐赠列表？一个人扫码付款之后，自动同步“付款人、付款日期、付款金额、付款渠道”到捐赠列表里，这个要坐下来估计要耗费很久吧，适配每个第三方支付的api。。。。（狗头）

**Comment by hifocus** [comment]
@Littlegolden 这非常困难，而且相关 API 并没有公开。
