### ISSUE TITLE
微信扫描二维码之后不会跳转到转账了

### ISSUE THREAD

**Issue by ruibaby** [hifocus/merger#16]
二维码：

![sponsor](https://halo.run/upload/2020/05/sponsor-a1a0693f1ab245edbbed4bd7756459e3.png)

地址：

http://sponsor.halo.run

> 另外，之前那个 pay.ryanc.cc 已经挂了，你可以在文档换成 `http://sponsor.halo.run`。

**Comment by hifocus** [comment]
非常抱歉一直没有留意到你的 issue。

目前不清楚导致出现你上方二维码微信扫码不显示付款码问题的原因，但是似乎和 CloudFlare 有关；支付方式按钮相关代码变成了：`<a href="#showqrcode" class="btn btn-primary" id="tenpaybtn" onclick="if (!window.__cfRLUnblockHandlers) return false; opentenpay()" data-cf-modified-2dd5ace3114fb388ebe5ff36-=""><svg class="icon" aria-hidden="true">`，并非原来的相关代码。

这个更改似乎是 CloudFlare 的 Rocket Loader 导致的；Rocket Loader 虽然可以宣称加快页面加载速度，但是在中国大陆网络环境下，加载 Rocket Loader js 文件的域名 `ajax.cloudflare.com` 加载异常缓慢，反而大幅拖慢了速度，所以无论如何是不建议开启的。

我将你在上方链接里的付款信息复制到最新的 merger 里面，测试可以完美使用（QQ、微信、支付宝、浏览器端），你也可以试试：https://donate-to-halo-organization-merger-files.vercel.app/demo.html （[二维码](https://www.zhihu.com/qrcode?url=https%3A%2F%2Fdonate-to-halo-organization-merger-files.vercel.app%2Fdemo.html)），同时官方演示页面 https://demo.qrcdn.com 也没有出现问题。

虽然这个问题的出现也有一部分是因为我代码不够规范导致的，但是暂时来说烦请**禁用 Rocket Loader 再重试**。

**Comment by hifocus** [comment]
演示页面地址将于稍后更改；但是这边还是建议你做一个重定向。如果频繁出现演示页面不可用的情况，将会直接删除。
