### ISSUE TITLE
建议按UA自动跳转后，依然可以关闭二维码

### ISSUE THREAD

**Issue by Chandler-Lu** [hifocus/merger#17]
很多时候，只是通过微信这个介质将支付网站的链接发给对方，但是对方未必会选择微信支付。
目前，在微信打开二维码后，无法回到选择支付方式的主页面，不知是否可以增加相关选项，允许按UA跳转后，点击二维码外部空白处依然可以回到支付方式的选择页面。谢谢

**Comment by hifocus** [comment]
以我的 merger 页面为例：https://demo.qrcdn.com
- 可以以两种方式分享：直接给予链接或者给予二维码

#### 直接给予链接
- 用户在微信内打开即为微信收款二维码
- 用户在任何非 QQ、支付宝客户端内打开即为通用页面

#### 给予二维码
- 使用各类二维码生成工具生成指向 https://demo.qrcdn.com 的二维码
- 将二维码发给用户
- 用户直接在微信内长按二维码识别，即为微信收款二维码
- 用户保存图片、截图，在 QQ、支付宝内打开，即为对应二维码

merger 的设计里一直都是：在任一客户端打开同一个网址（通过输入网址、扫描二维码均可），所展现的界面一定为最优。
如果识别到在支持的客户端内打开，则会焊死车门，避免用户误操作导致支付无法完成，也是为了界面简洁性和易用性。

通过发送链接的方式，对方必须懂得 “在 QQ、支付宝 聊天界面内输入并发送含有链接的消息，并且点击” 这种方法，所以我认为并非最直接、简便、不易出错的方式。

建议使用二维码生成工具（如 cli.im）代替发送链接，则可以在所有（Paypal 除外）客户端实现完美支持。
当然也可以建议用户使用外部浏览器打开 merger 页面，自行选择支付方式再截图、在相应的客户端内识别二维码支付。

**Comment by Chandler-Lu** [comment]
明白您的意思了，再次感谢！

**Comment by hifocus** [comment]
@Chandler-Lu 你客气了，感谢支持。
