### ISSUE TITLE
请问怎么集成到 hexo 的主题中？

### ISSUE THREAD

**Issue by 1an8r0wn** [hifocus/merger#6]
RT.
我看完了中文文档之后没有发现怎么把这个项目集成到 hexo 的主题中，我想替换掉 theme-ad 的 reward。
请问是有直接引用的用法吗？比如 iframe？还是要自己重新写到主题里面去？

**Comment by hifocus** [comment]
> RT.
> 我看完了中文文档之后没有发现怎么把这个项目集成到 hexo 的主题中，我想替换掉 theme-ad 的 reward。
> 请问是有直接引用的用法吗？比如 iframe？还是要自己重新写到主题里面去？

理论上可以通过 iframe 引用，但是效果不佳。如下图：

![image](https://user-images.githubusercontent.com/30528433/56631590-871e3500-6688-11e9-9619-dccb86ae86cc.png)

仅仅建议将 merger url 生成一个二维码，然后直接填入主题配置文件内的 alipay 一项中即可。还可以修改描述文字，更清楚地引导用户。

https://www.justhx.com/happy-cloudy-days.html 的打赏效果按钮如下：
![image](https://user-images.githubusercontent.com/30528433/56631653-cfd5ee00-6688-11e9-8ad2-8c5684f124d4.png)
