### ISSUE TITLE
可以做一个z-blog的插件吗?

### ISSUE THREAD

**Issue by lqhorochi** [hifocus/merger#7]
可以做一个z-blog的插件吗?

**Comment by hifocus** [comment]
因为 merger 属于 html 页面，可以自行部署，但是没办法 “嵌入” 到某一种博客程序里面去。

建议的做法是在主题内相应位置创建一个按钮，然后 `<a href="https://yoursite.com/merger.html" target="_blank">` 这样子将访客引导到捐赠页面。
