### ISSUE TITLE
有办法三码合一吗

### ISSUE THREAD

**Issue by lovezm** [hifocus/merger#8]

**Comment by hifocus** [comment]
请参见文档：https://merger.justhx.com/#/

> 你可以为你的 merger 生成一张二维码 (查看示例)，或者直接把你的 merger 链接发送给对方。merger 会通过 User Agent 识别对方的客户端，随即展示相应的内容。

简单来说就是完成配置和部署以后，使用任意二维码生成工具（如 [cli.im](https://cli.im)）为你的 merger 站点生成一个二维码，就已经完成了 “三码合一”；merger 在三码合一的基础上，额外加上了对 Paypal 的支持。

对于 merger 在不同客户端下的表现，可以参考[这张图片](https://ae01.alicdn.com/kf/UTB8hFq3KlahduJk43Jaq6zM8FXaR.jpg)。
